# Generated by Django 6.1.1 on 2026-10-08 09:26

import django.db.models.deletion
import leave.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "days_per_year",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Days allowed each year. 0 means there is no fixed number (for example unpaid leave).",
                    ),
                ),
                (
                    "counting",
                    models.CharField(
                        choices=[
                            ("working", "Working days"),
                            ("calendar", "Calendar days"),
                        ],
                        default="working",
                        max_length=10,
                    ),
                ),
                (
                    "needs_balance",
                    models.BooleanField(
                        default=True,
                        help_text="When ticked, nobody but the Manager can ask for more days than they have left.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SickLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_day", models.DateField(verbose_name="first day off sick")),
                (
                    "last_day",
                    models.DateField(
                        help_text="Change it later if they come back earlier or later.",
                        verbose_name="expected last day off",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Do not write medical details here."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("certificate_needed", "Sick sheet needed"),
                            ("certificate_received", "Sick sheet received"),
                            ("accepted", "Accepted"),
                            ("not_accepted", "Not accepted"),
                        ],
                        db_index=True,
                        default="certificate_needed",
                        max_length=30,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sick_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-first_day", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SickNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, upload_to=leave.models.sick_note_path),
                ),
                ("original_name", models.CharField(max_length=200)),
                ("mime_type", models.CharField(max_length=50)),
                ("size_bytes", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the file was deleted under the keep period.",
                        null=True,
                    ),
                ),
                (
                    "sick_leave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="leave.sickleave",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="first day off")),
                ("end_date", models.DateField(verbose_name="last day off")),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Days counted against the allowance.",
                        max_digits=5,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("rejected", "Not approved"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        help_text="The supervisor who decides. Empty means the Manager decides.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="leave_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("days", models.DecimalField(decimal_places=1, max_digits=5)),
                ("set_at", models.DateTimeField(auto_now=True)),
                (
                    "set_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allowances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "leave_type", "year"),
                        name="one_allowance_per_person_type_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("days__gte", 0)),
                        name="allowance_not_negative",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sickleave",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_day__gte", models.F("first_day"))),
                name="sick_last_after_first",
            ),
        ),
    ]
