# Generated by Django 6.1.1 on 2026-10-08 12:29

import leave.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_seed_leave_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sicknote",
            name="file",
            field=models.FileField(
                blank=True,
                storage=leave.models.sick_note_storage,
                upload_to=leave.models.sick_note_path,
            ),
        ),
    ]
