# Generated by Django 6.1.1 on 2026-10-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0003_alter_sicknote_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="days_given",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Days the Manager gave. Empty until decided.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="last_day_given",
            field=models.DateField(
                blank=True,
                help_text="Last day off, counted from the days given.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="days",
            field=models.DecimalField(
                decimal_places=1, help_text="Days asked for.", max_digits=5
            ),
        ),
    ]
