# Generated by Django 6.1.1 on 2026-10-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issue", "Client issue"),
                            ("feedback", "Client feedback"),
                            ("item", "Item"),
                            ("payroll", "Payroll"),
                            ("other", "Other matter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "note",
                    models.TextField(
                        help_text="What the Secretary needs from the Manager."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("seen", "Seen by Manager"),
                            ("sent_back", "Sent back to Secretary"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("raised_at", models.DateTimeField(auto_now_add=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-raised_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EscalationReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="escalations.escalation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "escalation replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="escalation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("status", "resolved"), _negated=True),
                    ("object_id__isnull", False),
                ),
                fields=("content_type", "object_id"),
                name="one_open_escalation_per_record",
            ),
        ),
        migrations.AddConstraint(
            model_name="escalation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "other"),
                    models.Q(
                        ("content_type__isnull", False), ("object_id__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="escalation_record_required_unless_other",
            ),
        ),
    ]
