# Generated by Django 6.1.1 on 2026-10-07 11:04

import core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("file", models.FileField(upload_to=core.models.attachment_path)),
                ("original_name", models.CharField(max_length=200)),
                ("mime_type", models.CharField(max_length=50)),
                ("size_bytes", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_attach_content_d3cac2_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "mime_type__in",
                                ("application/pdf", "image/jpeg", "image/png"),
                            )
                        ),
                        name="attachment_allowed_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("size_bytes__lte", 5242880)),
                        name="attachment_max_size",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_role", models.CharField(blank=True, max_length=20)),
                ("action", models.CharField(db_index=True, max_length=60)),
                ("entity_type", models.CharField(max_length=60)),
                ("entity_id", models.CharField(max_length=40)),
                ("summary", models.CharField(max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "confidential",
                    models.BooleanField(
                        default=False,
                        help_text="Payroll entries: only Secretary and Manager may see them.",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="core_auditl_entity__244637_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=150)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "kra_pin",
                    models.CharField(blank=True, max_length=20, verbose_name="KRA PIN"),
                ),
                ("logo", models.FileField(blank=True, upload_to="company/")),
                (
                    "payment_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Bank or paybill details printed on invoices.",
                    ),
                ),
                ("vat_registered", models.BooleanField(default=False)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("16.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("invoice_due_days", models.PositiveSmallIntegerField(default=14)),
                ("expense_approval_enabled", models.BooleanField(default=False)),
                (
                    "expense_approval_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_checks_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "company settings",
                "verbose_name_plural": "company settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="companysettings_single_row"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("vat_rate__gte", 0), ("vat_rate__lte", 100)
                        ),
                        name="companysettings_vat_rate_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expense_approval_limit__isnull", True),
                            ("expense_approval_limit__gt", 0),
                            _connector="OR",
                        ),
                        name="companysettings_expense_limit_positive",
                    ),
                ],
            },
        ),
    ]
