# Generated by Django 6.1.1 on 2026-10-08 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="late_after_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Someone who signs in more than this many minutes after their shift starts is marked late.",
                verbose_name="late after (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="sick_note_due_days",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="A reminder goes out if no sick sheet has been uploaded this many days after sick leave starts.",
                verbose_name="sick sheet expected within (days)",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="sick_note_keep_days",
            field=models.PositiveSmallIntegerField(
                default=365,
                help_text="Sick sheet files are deleted after this many days. The dates of the sick leave are kept.",
                validators=[django.core.validators.MinValueValidator(30)],
                verbose_name="keep sick sheets for (days)",
            ),
        ),
    ]
