# Generated by Django 6.1.1 on 2026-10-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="decision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("recorded", "Recorded"),
                    ("awaiting_approval", "Awaiting Manager approval"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="recorded",
                max_length=20,
            ),
        ),
    ]
