# Generated by Django 6.1.1 on 2026-10-07 11:04

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "condition_note",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="condition"
                    ),
                ),
                ("storage_location", models.CharField(blank=True, max_length=120)),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="minimum stock level"
                    ),
                ),
                (
                    "returnable",
                    models.BooleanField(
                        default=False,
                        help_text="Ticked: radios, torches. Not ticked: uniforms, boots (issued to keep).",
                        verbose_name="must be returned",
                    ),
                ),
                ("needs_manager_approval", models.BooleanField(default=False)),
                ("flag_changed_at", models.DateTimeField(blank=True, null=True)),
                ("qty_available", models.PositiveIntegerField(default=0)),
                (
                    "qty_reserved",
                    models.PositiveIntegerField(
                        default=0, verbose_name="waiting for collection"
                    ),
                ),
                ("qty_issued", models.PositiveIntegerField(default=0)),
                ("qty_damaged", models.PositiveIntegerField(default=0)),
                ("qty_lost", models.PositiveIntegerField(default=0)),
                ("low_stock_notified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.category",
                    ),
                ),
                (
                    "flag_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_role", models.CharField(max_length=20)),
                (
                    "qty_requested",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("qty_issued", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_manager", "Waiting for Manager"),
                            ("pending", "Item request pending"),
                            ("ready", "Approved - collect from Secretary"),
                            ("issued", "Item issued"),
                            (
                                "return_claimed",
                                "Item returned - awaiting Secretary approval",
                            ),
                            ("returned", "Item returned"),
                            ("lost", "Item recorded as lost"),
                            ("rejected", "Request rejected"),
                            ("cancelled", "Request cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("manager_decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.TextField(blank=True)),
                (
                    "expected_return_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("handed_over_at", models.DateTimeField(blank=True, null=True)),
                ("return_claimed_at", models.DateTimeField(blank=True, null=True)),
                ("return_approved_at", models.DateTimeField(blank=True, null=True)),
                ("qty_returned_good", models.PositiveIntegerField(default=0)),
                ("qty_returned_damaged", models.PositiveIntegerField(default=0)),
                ("qty_lost", models.PositiveIntegerField(default=0)),
                ("return_notes", models.TextField(blank=True)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handed_over_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="inventory.item",
                    ),
                ),
                (
                    "manager_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("added", "Added stock"),
                            ("written_off", "Written off"),
                            ("damaged", "Marked damaged"),
                            ("repaired", "Marked repaired"),
                            ("reserved", "Approved (waiting for collection)"),
                            ("released", "Approval cancelled"),
                            ("issued", "Handed over"),
                            ("returned_good", "Returned in good condition"),
                            ("returned_damaged", "Returned damaged"),
                            ("lost", "Recorded as lost"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("before", models.JSONField()),
                ("after", models.JSONField()),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.item",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.itemrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("qty_available__gte", 0),
                    ("qty_damaged__gte", 0),
                    ("qty_issued__gte", 0),
                    ("qty_lost__gte", 0),
                    ("qty_reserved__gte", 0),
                ),
                name="item_quantities_not_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="itemrequest",
            index=models.Index(
                fields=["requester", "-created_at"],
                name="inventory_i_request_063e10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemrequest",
            index=models.Index(
                fields=["item", "status"], name="inventory_i_item_id_1f60ed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_requested__gt", 0)),
                name="itemrequest_qty_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("qty_issued__isnull", True),
                    models.Q(
                        ("qty_issued__gt", 0),
                        ("qty_issued__lte", models.F("qty_requested")),
                    ),
                    _connector="OR",
                ),
                name="itemrequest_issued_within_requested",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("qty_lost", 0),
                        ("qty_returned_damaged", 0),
                        ("qty_returned_good", 0),
                    ),
                    (
                        "qty_issued__gte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("qty_returned_good"),
                                "+",
                                models.F("qty_returned_damaged"),
                            ),
                            "+",
                            models.F("qty_lost"),
                        ),
                    ),
                    _connector="OR",
                ),
                name="itemrequest_returns_within_issued",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["item", "-at"], name="inventory_s_item_id_cef3ce_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stockmovement_quantity_positive",
            ),
        ),
    ]
