# Generated by Django 6.1.1 on 2026-10-08 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        ("tracking", "0002_site_address_site_details_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OBEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, help_text="When it happened."),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("shift_start", "Shift started"),
                            ("handover", "Handover to next guard"),
                            ("patrol", "Patrol done"),
                            ("visitor", "Visitor or vehicle"),
                            ("delivery", "Delivery or keys"),
                            ("alarm", "Alarm or power problem"),
                            ("incident", "Incident"),
                            ("site_visit", "Supervisor visit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("written_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corrects",
                    models.ForeignKey(
                        blank=True,
                        help_text="The earlier entry this one corrects.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="operations.obentry",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="incidents.incident",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ob_entries",
                        to="tracking.site",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ob_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OB entry",
                "verbose_name_plural": "OB entries",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visited_at", models.DateTimeField(db_index=True)),
                (
                    "checks_done",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Codes from SiteVisit.CHECKS that were fine.",
                    ),
                ),
                (
                    "welfare_check_done",
                    models.BooleanField(
                        default=False, verbose_name="welfare check done"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guards_seen",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="tracking.site",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visited_at", "-id"],
            },
        ),
    ]
