# Generated by Django 6.1.1 on 2026-10-07 07:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "radius_m",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="How close counts as ON LOCATION. Between 5 and 50 metres. 30 suits most sites.",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="on-location radius (metres)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "audit entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "own_hours",
                    models.BooleanField(
                        default=False,
                        help_text="Use this person's own working hours instead of the site's.",
                    ),
                ),
                ("tracking_on", models.BooleanField(default=False)),
                ("tracking_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the person used the site.",
                        null=True,
                    ),
                ),
                ("last_ping_at", models.DateTimeField(blank=True, null=True)),
                ("last_latitude", models.FloatField(blank=True, null=True)),
                ("last_longitude", models.FloatField(blank=True, null=True)),
                ("last_accuracy_m", models.FloatField(blank=True, null=True)),
                ("last_distance_m", models.FloatField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on", "On location"),
                            ("near", "Near location"),
                            ("off", "Off location"),
                            ("weak", "GPS weak"),
                            ("waiting", "Waiting for GPS"),
                            ("lost", "Signal lost"),
                            ("tracking_off", "Tracking off"),
                            ("no_site", "No site assigned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people",
                        to="tracking.site",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("off_location", "Off location"),
                            ("tracking_off", "Location not turned on"),
                            ("signal_lost", "Location updates stopped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("user", "kind"),
                        name="one_open_alert_per_kind",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LocationPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, help_text="Server time the update arrived."
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(help_text="Time the phone took the reading."),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accuracy_m", models.FloatField()),
                ("distance_m", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on", "On location"),
                            ("near", "Near location"),
                            ("off", "Off location"),
                            ("weak", "GPS weak"),
                            ("waiting", "Waiting for GPS"),
                            ("lost", "Signal lost"),
                            ("tracking_off", "Tracking off"),
                            ("no_site", "No site assigned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        blank=True,
                        help_text="Why this reading looks wrong, if it does.",
                        max_length=120,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_pings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tracking.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-received_at"],
                        name="tracking_lo_user_id_a702be_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="tracking.site",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_hours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("site__isnull", False), ("user__isnull", True)),
                            models.Q(("site__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="workhours_site_xor_user",
                    ),
                    models.UniqueConstraint(
                        fields=("site", "weekday"), name="workhours_one_per_site_day"
                    ),
                    models.UniqueConstraint(
                        fields=("user", "weekday"), name="workhours_one_per_user_day"
                    ),
                ],
            },
        ),
    ]
