# Generated by Django 6.1.1 on 2026-10-08 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def start_current_postings(apps, schema_editor):
    """People already assigned to a site get an open posting, so the history starts today."""
    from django.utils import timezone

    Profile = apps.get_model("tracking", "TrackingProfile")
    Posting = apps.get_model("tracking", "SitePosting")
    now = timezone.now()
    Posting.objects.bulk_create(
        Posting(user_id=p.user_id, site_id=p.site_id, started_at=now) for p in Profile.objects.filter(site__isnull=False)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="address / directions"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="details_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="details_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="emergency_contacts",
            field=models.TextField(
                blank=True,
                help_text="One per line, for example: Kondele Police Post 0712 000 000.",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="guards_needed",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Fewer guards available than this shows the site as SHORT-STAFFED.",
                verbose_name="guards needed per shift",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="What guards must do at this site.",
                verbose_name="site instructions",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="The supervisor who looks after this site.",
                limit_choices_to={"role": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_sites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SitePosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postings",
                        to="tracking.site",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("user",),
                        name="one_current_posting_per_person",
                    )
                ],
            },
        ),
        migrations.RunPython(start_current_postings, migrations.RunPython.noop),
    ]
