# Generated by Django 6.1.1 on 2026-10-08 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracking", "0002_site_address_site_details_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="date and time it happened"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("theft", "Theft"),
                            ("break_in", "Break-in"),
                            ("fire", "Fire"),
                            ("injury", "Injury"),
                            ("trespass", "Trespass"),
                            ("damage", "Damage"),
                            ("force_arrest", "Use of force or arrest"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("what_happened", models.TextField()),
                (
                    "who_involved",
                    models.TextField(blank=True, verbose_name="who was involved"),
                ),
                ("action_taken", models.TextField(blank=True)),
                (
                    "police_reported",
                    models.BooleanField(
                        default=False, verbose_name="reported to the police"
                    ),
                ),
                (
                    "police_ob_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="police OB number"
                    ),
                ),
                (
                    "client_told",
                    models.BooleanField(default=False, verbose_name="client was told"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("supervisor_reviewed", "Reviewed by supervisor"),
                            ("manager_reviewed", "Reviewed by manager"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("supervisor_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("manager_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="tracking.site",
                    ),
                ),
                (
                    "supervisor_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IncidentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("status_from", models.CharField(blank=True, max_length=20)),
                ("status_to", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["site", "-occurred_at"], name="incidents_i_site_id_0f0c46_idx"
            ),
        ),
    ]
