# Generated by Django 6.1.1 on 2026-10-07 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("high", "Important")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("link_url", models.CharField(blank=True, max_length=300)),
                ("entity_type", models.CharField(blank=True, max_length=60)),
                ("entity_id", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "-created_at"],
                        name="notificatio_recipie_ce9d56_idx",
                    )
                ],
            },
        ),
    ]
