# Generated by Django 6.1.1 on 2026-10-08 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracking", "0002_site_address_site_details_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("completed_at", models.DateTimeField()),
                ("present", models.PositiveIntegerField(default=0)),
                ("late", models.PositiveIntegerField(default=0)),
                ("absent", models.PositiveIntegerField(default=0)),
                ("on_leave", models.PositiveIntegerField(default=0)),
                ("sick", models.PositiveIntegerField(default=0)),
                (
                    "completed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="The day the shift started."
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("absent", "Absent"),
                            ("on_leave", "On leave"),
                            ("sick", "Sick"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_supervisor", "Waiting for supervisor"),
                            ("waiting_manager", "Waiting for Manager"),
                            ("rejected", "Not accepted by supervisor"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("gps", "Signed in at the site"),
                            ("supervisor", "Marked by supervisor"),
                            ("office", "Marked by the Manager"),
                            ("system", "Recorded when the day was completed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "signed_in_at",
                    models.DateTimeField(
                        blank=True, help_text="Server time of the sign-in.", null=True
                    ),
                ),
                ("shift_start", models.DateTimeField(blank=True, null=True)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                ("location_status", models.CharField(blank=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("supervisor_decided_at", models.DateTimeField(blank=True, null=True)),
                ("supervisor_note", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance",
                        to="tracking.site",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approves this sign-in. Empty means it goes straight to the Manager.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "user__first_name"],
                "indexes": [
                    models.Index(
                        fields=["date", "status"], name="attendance__date_64c311_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="one_attendance_per_person_day"
                    )
                ],
            },
        ),
    ]
