# Generated by Django 6.1.1 on 2026-10-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="manual_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_signal", "No signal"),
                    ("phone", "Phone problem"),
                    ("wrong_place", "GPS shows wrong place"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="reason for no location",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="sign_out_distance_m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="sign_out_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gps", "Signed out with location"),
                    ("no_location", "Signed out without location"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="sign_out_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_signal", "No signal"),
                    ("phone", "Phone problem"),
                    ("wrong_place", "GPS shows wrong place"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="signed_out_at",
            field=models.DateTimeField(
                blank=True, help_text="Server time of the sign-out.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("gps", "Signed in at the site"),
                    ("no_location", "Signed in without location"),
                    ("supervisor", "Marked by supervisor"),
                    ("office", "Marked by the Manager"),
                    ("system", "Recorded when the day was completed"),
                ],
                max_length=20,
            ),
        ),
    ]
